import { HeroTitle } from "./Hero";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const Faq = () => {
  return (
    <div className="py-10">
      <div className="flex justify-center">
              <div className="tag">FAQ</div>
        </div>
      <HeroTitle className="grid">Frequently Asked Questions</HeroTitle>
      <div className="lg:max-w-[1150px] mx-auto py-16">
        <Accordion type="single" collapsible>
          <AccordionItem value="item-1">
            <AccordionTrigger>
              How does the tool help generate engaging tweets?
            </AccordionTrigger>
            <AccordionContent>
              Our tool provides suggestions based on popular topics and user engagement patterns to help you create tweets that are likely to engage your audience.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger>
              Can I customize the tweets to fit my niche or industry?
            </AccordionTrigger>
            <AccordionContent>
              Yes, you can input specific keywords and topics related to your niche or industry. The tool will generate tweets that align with your focus area.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger>
              How often can I generate tweets using this service?
            </AccordionTrigger>
            <AccordionContent>
              You can generate tweets as often as you like based on your subscription plan. Whether you need tweets daily, weekly, or even more frequently, the tool is available for you.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger>
              Can I schedule the tweets generated by the tool?
            </AccordionTrigger>
            <AccordionContent>
              Yes, our platform allows you to schedule tweets. You can plan your social media posts in advance to ensure consistent engagement with your audience.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-5">
            <AccordionTrigger>
              How can I measure the effectiveness of my tweets?
            </AccordionTrigger>
            <AccordionContent>
              Our platform includes basic analytics tools to track the performance of your tweets. You can see metrics like retweets, likes, and overall engagement to understand how well your tweets are performing.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
};

export default Faq;