import { HeroTitle } from "./Hero";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const Faq = () => {
  return (
    <div className="py-20">
      <HeroTitle className="grid">Frequently Asked Questions</HeroTitle>
      <div className="lg:max-w-[1150px] mx-auto py-16">
        <Accordion type="single" collapsible>
          <AccordionItem value="item-1">
            <AccordionTrigger>
              How does the AI generate viral tweets?
            </AccordionTrigger>
            <AccordionContent>
              Our AI uses advanced algorithms and machine learning techniques to
              analyze trending topics, engagement metrics, and user preferences.
              By understanding what makes tweets go viral, our AI crafts
              engaging and shareable content tailored to your audience.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-2">
            <AccordionTrigger>
              Can the AI tailor tweets to my specific niche or industry?
            </AccordionTrigger>
            <AccordionContent>
              Yes, our AI can be customized to focus on your specific niche or
              industry. By inputting relevant keywords and topics, the AI
              generates tweets that are aligned with your brand and resonate
              with your target audience.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-3">
            <AccordionTrigger>
              How often can I generate tweets using this service?
            </AccordionTrigger>
            <AccordionContent>
              You can generate an unlimited number of tweets depending on your
              subscription plan. Whether you need daily, weekly, or even hourly
              tweets, our AI is ready to provide you with fresh, engaging
              content whenever you need it.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-4">
            <AccordionTrigger>
              Is there a way to schedule the tweets generated by the AI?
            </AccordionTrigger>
            <AccordionContent>
              Absolutely! Our platform integrates with popular social media
              management tools, allowing you to schedule tweets directly from
              our interface. This way, you can plan your social media strategy
              in advance and ensure consistent engagement.
            </AccordionContent>
          </AccordionItem>
          <AccordionItem value="item-5">
            <AccordionTrigger>
              How do I know if the generated tweets are effective?
            </AccordionTrigger>
            <AccordionContent>
              Our platform includes analytics tools that track the performance
              of your tweets. You'll receive insights on engagement rates,
              retweets, likes, and other key metrics, helping you understand
              what works best and refine your strategy accordingly.
            </AccordionContent>
          </AccordionItem>
        </Accordion>
      </div>
    </div>
  );
};

export default Faq;
